### ISSUE TITLE
MasonryGrid is undefined

### ISSUE THREAD

**Issue by saltyandsmiling** [naver/egjs-grid#41]
## Description

Hey y'all. The issue I'm experiencing is that on first render MasonryGrid comes through undefined causing my app to crash. I've fixed the issue by adding a `{Boolean(MasonryGrid) && ...(<MasonryGrid>....` where I'm using the library but that seems odd. I'm putting this here to see if anyone else is experiencing the issue or if this is a known problem. 

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

## Steps to check or reproduce

I'm just importing MasonryGrid into my react component and using it with "gap" and "column" props.

**Comment by saltyandsmiling** [comment]
So it looks like this was a SSR issue and inside of a React/Next setup I have to make sure this code is ran on the clientside using the following code. 

`const [mounted, setMounted] = useState(false);`
` useEffect(() => {
    setMounted(true);
  }, []);
`

then in the render 

`{mounted && (
      <MasonryGrid gap={16} column={2}>
            {children}
      </MasonryGrid>
`

**Comment by daybrush** [comment]
@saltyandsmiling 

Sorry. it's commonjs issue.

Try `@egjs/react-grid@1.5.1-beta.0` (`@beta`) Thank you :)
