### ISSUE TITLE
Sveltekit: <MasonryGrid> is not a valid SSR component

### ISSUE THREAD

**Issue by callumflack** [naver/egjs-grid#45]
## Description

Does not work with Sveltekit (via Vite).

## Steps to check or reproduce

Install it on a fresh Sveltekit starter.

I tried adding as a `devDep` and an `dep` to no avail. I also tried adding the package to the vite's `optimizeDeps` in the sveltekit config, to no avail.

![image](https://user-images.githubusercontent.com/749885/142342621-e98f6c00-c976-4073-9446-684be38843e4.png)

**Comment by daybrush** [comment]
@callumflack 


Thank you. I'll fix it soon.

**Comment by daybrush** [comment]
@callumflack 


Try @egjs/svelte-grid@1.6.1-beta.0

**Comment by callumflack** [comment]
Thank you @daybrush !

**Comment by daybrush** [comment]
@callumflack 

`@egjs/svelte-grid` 1.7.0 is released. There is no difference. Thank you :)
