### ISSUE TITLE
build failed with SvelteKit latest version

### ISSUE THREAD

**Issue by GrassHopper42** [naver/egjs-grid#72]
## Description

It seems to be similar with <https://github.com/naver/egjs-infinitegrid/issues/505#issue-1334705429>

this is error log
```
/* empty css                                                    */import { MasonryGrid as MasonryGrid$1 } from "@egjs/grid";
                                                                           ^^^^^^^^^^^
SyntaxError: Named export 'MasonryGrid' not found. The requested module '@egjs/grid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@egjs/grid';
const { MasonryGrid: MasonryGrid$1 } = pkg;
```
## Steps to check or reproduce

update to svelte-kit latest version
and npm run build

**Comment by GrassHopper42** [comment]
@daybrush 
I copy your works from infinitegrid and committed in my repository.
Can I PR?

**Comment by daybrush** [comment]
@GrassHopper42 

Thank you for doing it. If you write a PR, I will resolve it.

**Comment by daybrush** [comment]
@GrassHopper42 

svelte-grid's new version is released. Thank you :)
