### ISSUE TITLE
Can I change the container of MasonryGrid? 

### ISSUE THREAD

**Issue by jyooj08** [naver/egjs-grid#91]
## Description
When using egjs/react-grid, the container of MasonryGrid is set to `div` by default. Can I change this to `ul`?

**Comment by daybrush** [comment]
@jyooj08 

In the case of react, there is a prop called tag. (Default: "div")
So try changing the tag to "ul".

**Comment by jyooj08** [comment]
Thank you @daybrush, it works well😊
