### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by stepanoves** [naver/egjs-grid#95]
## Description
I would like to bring to your attention the compatibility issue with your library in relation to Angular 16. Currently, your library is not compatible with Angular 16 due to the lack of support for esm 2015.
We highly appreciate the work you have put into this library and would like to inquire if you have any plans to release an update that would make it compatible with Angular 16. We would like to continue using your library in our project, and compatibility with the latest version of Angular is crucial for us.
If you have any plans or time to address this issue, please let us know. 
Thank you for your work and attention to this matter. We hope for a positive response from you.

**Comment by daybrush** [comment]
@stepanoves 

yes.  We are upgrading egjs components to Angular 15~16. (A little time consuming.)

First, we will enable ivy mode so that it is supported in Angular16.

**Comment by ilisko** [comment]
@daybrush

Hello :) Can i ask you for some date when this fix will be released, as we postponed using library for now.. Thx in advance.

**Comment by malangfox** [comment]
@stepanoves @ilisko 

@egjs/ngx-grid version 1.14.2-beta.0 has been released.
Can you try using the latest beta version of @egjs/ngx-grid?

**Comment by ilisko** [comment]
Hello.. Thx for the update.. We are going to try it in next few days and test it.. After that I'm gona write you here the results :)

**Comment by ilisko** [comment]
@daybrush @malangfox 

We updated library and test our application.. Everything seems fine now. We are now waiting for you to make it official so that we can integrate once again in our application.. Please inform us when version is stable and ready to be updated.. Thank you again :)

**Comment by ilisko** [comment]
@daybrush @malangfox 

Hello, do you have any time estimation when this will be integrated into stable version ready to use :)

**Comment by malangfox** [comment]
@ilisko 

We have released the 1.14.2 version of @egjs/ngx-grid.
Try using the version above and leave a comment if you encounter any issues.
